CREATE TABLE FoodAndGroceryCategory(
   ProductID int primary key auto_increment,
   Product_Name            VARCHAR(32) NOT NULL
  ,Target                  VARCHAR(8) NOT NULL
  ,Star_Market             VARCHAR(8) NOT NULL
  ,Trader_Joes             VARCHAR(8) NOT NULL
  ,CVS                     VARCHAR(8) NOT NULL
  ,Taj_Mahal_Desi_Bazaar   VARCHAR(8) NOT NULL
  ,Patel_Brothers          VARCHAR(8) NOT NULL
  ,Hello_Brothers          VARCHAR(8) NOT NULL
  ,Punjab_Mini_Mart        VARCHAR(8) NOT NULL
  ,College_Convenience     VARCHAR(8) NOT NULL
  ,Wollastons_Market       VARCHAR(8) NOT NULL
  ,Wollastons_West_Village VARCHAR(8) NOT NULL
  ,Symphony_Market         VARCHAR(8) NOT NULL
  ,Symphony_Mart           VARCHAR(8) NOT NULL
  ,Costco                  VARCHAR(8) NOT NULL
  ,Walmart                 VARCHAR(8) NOT NULL
  ,TJ_Maxx                 VARCHAR(10) NOT NULL
  ,Burlington              VARCHAR(10) NOT NULL
  ,BestBuy                 VARCHAR(10) NOT NULL
);
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('White Bread','$1.29','$2.00','$2.00','$1.00','$3.00','$1.00','$3.00','$2.00','$1.00','$1.00','$2.00','$2.00','$3.00','$1.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Brown Bread','$1.29','$4.00','$1.00','$3.00','$1.00','$3.00','$2.00','$3.00','$3.00','$1.00','$2.00','$1.00','$2.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Pav Bhaji Bread','NA','NA','$3.00','NA','$4.00','$5.00','$3.00','$4.00','$3.00','$4.00','$3.00','$5.00','$3.00','NA','NA','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Sugar','$2.99','$6.00','$3.00','$4.00','$5.00','$6.00','$3.00','$6.00','$6.00','$3.00','$3.00','$5.00','$3.00','$6.00','$6.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Salt','$4.00','$5.00','$5.00','$3.00','$4.00','$5.00','$5.00','$5.00','$4.00','$5.00','$4.00','$4.00','$3.00','$5.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Canola Oil','$7.00','$5.00','$5.00','$6.00','$7.00','$6.00','$8.00','$8.00','$5.00','$5.00','$5.00','$7.00','$6.00','$5.00','$8.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Peanut Oil','$14.00','$15.00','$18.00','$18.00','$16.00','$18.00','$14.00','$14.00','$15.00','$19.00','$16.00','$20.00','$19.00','$16.00','$16.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Butter','$6.00','$6.00','$7.00','$8.00','$5.00','$7.00','$8.00','$8.00','$7.00','$6.00','$7.00','$5.00','$5.00','$6.00','$8.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Whole Milk 1Gal','$3.49','$3.00','$5.00','$5.00','$5.00','$3.00','$5.00','$4.00','$5.00','$3.00','$3.00','$5.00','$4.00','$4.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Chocolate Milk','$4.49','$5.00','$4.00','$3.00','$4.00','$5.00','$5.00','$4.00','$5.00','$3.00','$4.00','$3.00','$3.00','$3.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('White Eggs','$4.59','$5.00','$5.00','$3.00','$4.00','$4.00','$5.00','$3.00','$5.00','$4.00','$4.00','$4.00','$5.00','$5.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Brown Eggs','$4.79','$3.00','$5.00','$5.00','$4.00','$4.00','$3.00','$3.00','$4.00','$3.00','$4.00','$5.00','$5.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Yogurt','$3.00','$4.00','$5.00','$3.00','$3.00','$4.00','$5.00','$3.00','$4.00','$5.00','$4.00','$5.00','$4.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Paneer','NA','NA','NA','NA','$9.00','$9.00','$8.00','$9.00','$10.00','$10.00','$8.00','$8.00','$9.00','$8.00','$8.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Butter Milk','$5.00','$4.00','$4.00','$5.00','$4.00','$3.00','$4.00','$4.00','$5.00','$5.00','$5.00','$3.00','$4.00','$4.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Condensed Milk','$3.00','$3.00','$3.00','$5.00','$3.00','$3.00','$3.00','$3.00','$4.00','$3.00','$5.00','$5.00','$3.00','$4.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Cheese','$3.00','$4.00','$4.00','$4.00','$5.00','$3.00','$3.00','$4.00','$4.00','$3.00','$4.00','$3.00','$3.00','$5.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Chicken Breast','$13.00','$13.00','$14.00','$16.00','NA','NA','NA','NA','NA','$15.00','$11.00','$12.00','$16.00','$14.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Hamburger Pattice','$14.00','$12.00','$13.00','$12.00','NA','NA','NA','NA','NA','$12.00','$10.00','$15.00','$12.00','$12.00','$14.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Chicken Drumstick','$5.00','$5.00','$10.00','$4.00','$10.00','$10.00','$8.00','$8.00','$6.00','$10.00','$10.00','$8.00','$6.00','$8.00','$9.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Chicken Nuggets','$5.00','$7.00','$9.00','$10.00','$10.00','$5.00','$8.00','$4.00','$4.00','$10.00','$10.00','$8.00','$4.00','$5.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Sausage','$9.00','$8.00','$9.00','$9.00','$8.00','$9.00','$8.00','$9.00','$8.00','$9.00','$10.00','$8.00','$10.00','$8.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Bottled Water','$2.00','$2.00','$1.00','$2.00','$2.00','$1.00','$2.00','$1.00','$2.00','$1.00','$1.00','$1.00','$3.00','$3.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Diet Coke','$5.00','$3.00','$4.00','$4.00','$3.00','$5.00','$4.00','$5.00','$4.00','$5.00','$5.00','$4.00','$5.00','$3.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Mountain Dew','$4.00','$5.00','$3.00','$3.00','$5.00','$3.00','$3.00','$3.00','$5.00','$4.00','$3.00','$4.00','$3.00','$4.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Monster Can','$5.00','$3.00','$3.00','$5.00','$3.00','$5.00','$4.00','$3.00','$5.00','$3.00','$3.00','$4.00','$5.00','$5.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Potato','$2.00','$2.00','$1.00','$3.00','$3.00','$3.00','$3.00','$2.00','$1.00','$2.00','$2.00','$1.00','$1.00','$1.00','$1.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Tomato','$1.29','$2.00','$3.00','$1.00','$1.00','$2.00','$2.00','$2.00','$1.00','$3.00','$2.00','$2.00','$1.00','$2.00','$1.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Red Onion','$1.29','$1.00','$3.00','$2.00','$3.00','$3.00','$2.00','$2.00','$2.00','$3.00','$1.00','$2.00','$1.00','$1.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Lemon','$2.00','$3.00','$3.00','$1.00','$2.00','$1.00','$2.00','$3.00','$3.00','$3.00','$3.00','$3.00','$1.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Ginger','$2.00','$3.00','$1.00','$3.00','$2.00','$1.00','$1.00','$3.00','$3.00','$1.00','$3.00','$3.00','$1.00','$2.00','$1.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Corrianders','$1.00','$1.00','$4.00','$3.00','$2.00','$4.00','$4.00','$4.00','$4.00','$1.00','$2.00','$2.00','$2.00','$1.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Green Cabbage','$4.00','$1.00','$3.00','$2.00','$1.00','$4.00','$3.00','$4.00','$3.00','$1.00','$4.00','$4.00','$3.00','$4.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Apples','$1.00','$2.00','$1.00','$4.00','$3.00','$2.00','$4.00','$4.00','$4.00','$4.00','$1.00','$3.00','$3.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Bananas','$2.00','$2.00','$2.00','$2.00','$2.00','$2.00','$2.00','$2.00','$1.00','$2.00','$2.00','$2.00','$1.00','$1.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('French Beans','$1.00','$1.00','$1.00','$3.00','$3.00','$3.00','$1.00','$1.00','$1.00','$3.00','$3.00','$2.00','$4.00','$1.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Strawberry','$3.00','$5.00','$4.00','$5.00','$5.00','$5.00','$5.00','$5.00','$4.00','$3.00','$3.00','$3.00','$4.00','$3.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Oranges','$5.00','$5.00','$3.00','$4.00','$5.00','$4.00','$4.00','$4.00','$3.00','$5.00','$5.00','$5.00','$5.00','$4.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Red Beans','$5.00','$5.00','$3.00','$5.00','$3.00','$4.00','$3.00','$3.00','$3.00','$3.00','$3.00','$4.00','$5.00','$5.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Heinz Ketchup','$3.00','$3.00','$3.00','$5.00','$4.00','$4.00','$3.00','$3.00','$3.00','$5.00','$4.00','$3.00','$5.00','$5.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Maggi Noodles 1.23LB Pack','$6.00','$10.00','$10.00','$7.00','$7.00','$9.00','$10.00','$7.00','$9.00','$8.00','$6.00','$8.00','$9.00','$6.00','$7.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Ramen Noodles','$9.00','$10.00','$6.00','$8.00','$10.00','$7.00','$8.00','$9.00','$6.00','$7.00','$8.00','$9.00','$9.00','$9.00','$8.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Toor dal (Split Pigeon peas) 4LB','$6.00','$4.00','$5.00','$5.00','$5.00','$5.00','$5.00','$6.00','$5.00','$4.00','$4.00','$5.00','$4.00','$6.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Thick Poha 2LB','$5.00','$5.00','$4.00','$6.00','$5.00','$4.00','$6.00','$6.00','$5.00','$6.00','$4.00','$4.00','$4.00','$4.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Ginger & Garlic Paste','$1.00','$1.00','$1.00','$3.00','$1.00','$2.00','$1.00','$1.00','$1.00','$2.00','$1.00','$1.00','$1.00','$1.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Raw Almonds','$7.00','$5.00','$5.00','$8.00','$9.00','$8.00','$5.00','$5.00','$9.00','$7.00','$9.00','$5.00','$7.00','$7.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Cashew Pieces','$10.00','$9.00','$6.00','$7.00','$10.00','$8.00','$8.00','$8.00','$9.00','$7.00','$7.00','$8.00','$8.00','$10.00','$6.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Salted Pista','$5.00','$6.00','$7.00','$5.00','$5.00','$7.00','$7.00','$10.00','$10.00','$5.00','$7.00','$5.00','$8.00','$8.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Golden Raisins','$6.00','$6.00','$8.00','$6.00','$6.00','$5.00','$9.00','$7.00','$7.00','$6.00','$6.00','$9.00','$7.00','$8.00','$10.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Cumin Seeds','$4.00','$2.00','$3.00','$2.00','$4.00','$3.00','$2.00','$4.00','$2.00','$3.00','$2.00','$4.00','$2.00','$3.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Coriander Powder','$2.00','$3.00','$4.00','$4.00','$2.00','$3.00','$3.00','$2.00','$3.00','$2.00','$3.00','$4.00','$2.00','$2.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Vinegar','$2.00','$3.00','$2.00','$4.00','$4.00','$3.00','$4.00','$2.00','$3.00','$2.00','$4.00','$2.00','$2.00','$3.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Snickers','$4.00','$3.00','$4.00','$4.00','$4.00','$4.00','$4.00','$2.00','$2.00','$2.00','$3.00','$4.00','$4.00','$2.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Twix','$3.00','$3.00','$4.00','$3.00','$2.00','$2.00','$3.00','$2.00','$2.00','$3.00','$3.00','$3.00','$4.00','$3.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Hersheys','$3.00','$3.00','$4.00','$3.00','$4.00','$3.00','$4.00','$2.00','$4.00','$4.00','$2.00','$3.00','$4.00','$4.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Phulka Roti','NA','NA','NA','NA','$7.00','$6.00','$6.00','$8.00','$10.00','$10.00','$10.00','$10.00','$10.00','NA','NA','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Masala Mirch Roti','NA','NA','NA','NA','$10.00','NA','NA','NA','$10.99','$10.99','$10.99','NA','NA','NA','NA','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Aloo Paratha','$8.00','$9.00','$8.00','$10.00','$9.00','$9.00','$9.00','$9.00','$10.00','$8.00','$10.00','$8.00','$8.00','$9.00','$8.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Flour Tortillas','$2.00','$3.00','$2.00','$2.00','$4.00','$2.00','$2.00','$4.00','$3.00','$2.00','$3.00','$4.00','$4.00','$2.00','$2.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Chips Ahoy','$3.00','$3.00','$4.00','$4.00','$4.00','$4.00','$2.00','$4.00','$3.00','$2.00','$4.00','$3.00','$3.00','$2.00','$3.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Protein Bars','$2.00','$4.00','$2.00','$2.00','$4.00','$3.00','$3.00','$2.00','$3.00','$4.00','$2.00','$3.00','$2.00','$2.00','$4.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Cereal 18.8 OZ','$5.00','$7.00','$8.00','$5.00','$7.00','$7.00','$8.00','$9.00','$5.00','$7.00','$10.00','$6.00','$5.00','$9.00','$5.00','NA','NA','NA');
INSERT INTO FoodAndGroceryCategory(Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,TJ_Maxx,Burlington,BestBuy) VALUES ('Green Grapes 1.5LB','$4.79','$2.00','$3.00','$2.00','$3.00','$4.00','$4.00','$3.00','$3.00','$3.00','$2.00','$2.00','$3.00','$3.00','$2.00','NA','NA','NA');


