CREATE TABLE Miscellaneous(
   Misc_ID                 INTEGER  NOT NULL PRIMARY KEY 
  ,Product_Name            VARCHAR(19) NOT NULL
  ,Target                  VARCHAR(9) NOT NULL
  ,Star_Market             VARCHAR(7) NOT NULL
  ,Trader_Joes             VARCHAR(7) NOT NULL
  ,CVS                     VARCHAR(7) NOT NULL
  ,Taj_Mahal_Desi_Bazaar   VARCHAR(8) NOT NULL
  ,Patel_Brothers          VARCHAR(7) NOT NULL
  ,Hello_Brothers          VARCHAR(7) NOT NULL
  ,Punjab_Mini_Mart        VARCHAR(7) NOT NULL
  ,College_Convenience     VARCHAR(8) NOT NULL
  ,Wollastons_Market       VARCHAR(7) NOT NULL
  ,Wollastons_West_Village VARCHAR(8) NOT NULL
  ,Symphony_Market         VARCHAR(8) NOT NULL
  ,Symphony_Mart           VARCHAR(7) NOT NULL
  ,Costco                  VARCHAR(9) NOT NULL
  ,Walmart                 VARCHAR(9) NOT NULL
  ,T_J_Maxx                VARCHAR(7) NOT NULL
  ,Burlington              VARCHAR(8) NOT NULL
  ,Best_Buy                VARCHAR(10) NOT NULL
);
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (1,'CloseUp Toothpaste','$5.00','$8.00','$5.00','$5.00','$5.00','$5.00','$5.00','$8.00','$6.00','$5.00','$6.00','$7.00','$5.00','$6.00','$7.00','NA','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (2,'Bedsheet','$17.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$18.00','$20.00','$15','$17.00','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (3,'Comforter','$20.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$28.00','$21.00','$30','$25','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (4,'Hangers','$2.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$3.00','$2.00','$5','$5','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (5,'Snow Jacket','$151.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$142.00','$144.00','$95','$125','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (6,'Listerine Mouthwash','$8.00','$7.00','$9.00','$9.00','$10.00','$9.00','$7.00','$5.00','$10.00','$5.00','$10.00','$10.00','$9.00','$7.00','$10.00','$8','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (7,'Colgate','$6.00','$5.00','$6.00','$8.00','$6.00','$5.00','$6.00','$5.00','$5.00','$6.00','$6.00','$6.00','$5.00','$7.00','$5.00','$4','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (8,'Dove Soap','$4.00','$3.00','$3.00','$2.00','$3.00','$3.00','$2.00','$4.00','$4.00','$4.00','$3.00','$2.00','$4.00','$2.00','$4.00','$4','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (9,'Mattress','$137.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$127.00','$125.00','$300','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (10,'Bedframe','$48.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$47.00','$60.00','$50','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (11,'Drawer Dressers','$21.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$22.00','$21.00','$25','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (12,'Chair','$30.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$25.00','$25.00','$30','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (13,'Writing Table','$35.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$35.00','$35.00','$35','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (14,'Spatula','$3.00','$2.00','$4.00','$3.00','$4.00','$3.00','$4.00','$3.00','$4.00','$4.00','$4.00','$4.00','$3.00','$2.00','$2.00','$10','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (15,'Brita Water Filter','$24.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$35.00','$35.00','NA','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (16,'Egg Beater','$5.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$7.00','$7.00','$4','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (17,'Snow Boots','$50.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$70.00','$70.00','$65','$70','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (18,'Umbrella','$6.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$6.00','$8.00','$6','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (19,'Pillow','$5.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$3.00','$3.00','$5','$5','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (20,'Plastic Cups','$3.00','$2.00','$2.00','$1.00','$3.00','$1.00','$2.00','$1.00','$1.00','$3.00','$3.00','$1.00','$2.00','$3.00','$1.00','$3','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (21,'Pens','$2.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$1.00','$2.00','$2.00','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (22,'Pencils','$2.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$3.00','$2.00','$3.00','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (23,'Shampoo','$6.00','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','$3.00','$1.00','$3.00','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (24,'Body wash','$10.00','$7.00','$7.00','$8.00','$10.00','$7.00','$6.00','$5.00','$6.00','$9.00','$8.00','$10.00','$6.00','$8.00','$5.00','$8.00','NA','NA');
INSERT INTO Miscellaneous(Misc_ID,Product_Name,Target,Star_Market,Trader_Joes,CVS,Taj_Mahal_Desi_Bazaar,Patel_Brothers,Hello_Brothers,Punjab_Mini_Mart,College_Convenience,Wollastons_Market,Wollastons_West_Village,Symphony_Market,Symphony_Mart,Costco,Walmart,T_J_Maxx,Burlington,Best_Buy) VALUES (25,'Toothbrush','$5.00','$3.00','$4.00','$4.00','$4.00','$3.00','$5.00','$3.00','$5.00','$5.00','$3.00','$3.00','$4.00','$4.00','$3.00','$3.00','NA','NA');

select * from miscellaneous;